name: chunk_norris
description: A powerful Dart library for progressive JSON hydration with chunked data loading, placeholders, and type safety.
version: 1.0.0
repository: https://github.com/Duit-Foundation/chunk_norris
issue_tracker: https://github.com/Duit-Foundation/chunk_norris/issues

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  meta: ^1.17.0
  collection: ^1.19.1
