name: post-merge

on:
  push:
    branches:
      - 'main'

jobs:
  post-merge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run tests with coverage
        run: dart pub global activate coverage && dart test --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.CHUNK_NORRIS_COVERALS_TOKEN }}
          path-to-lcov: coverage/lcov.info
          flag-name: UNIT
          parallel: true
          fail-on-error: false
  
  finish:
    needs: post-merge-test
    runs-on: ubuntu-latest
    steps:
      - name: Finish Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.CHUNK_NORRIS_COVERALS_TOKEN }}
          parallel-finished: true
          fail-on-error: false